// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/estrategias.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/estrategias.json').default>>>>
    }
    '/tareas.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/tareas.json').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@3.21.11__f647b8a9525dcd13c584bb6491155369/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}